// constants.ts
export const SET_USERS = "SET_USERS";
export const SELECT_USER = "SELECT_USER";
export const SELECT_ALL_USER = "SELECT_ALL_USER";

export const SET_ROBOT_INTERACT_CONFIG = "SET_ROBOT_INTERACT_CONFIG";
export const SELECT_INTERACT_LIKE_COMMENT = "SELECT_INTERACT_LIKE_COMMENT";
export const SET_INTERACT_NEWS_FEED = "SET_INTERACT_NEWS_FEED";
export const SET_INTERACT_WATCH = "SET_INTERACT_WATCH";
export const SET_INTERACT_FRIEND = "SET_INTERACT_FRIEND";
export const SET_INTERACT_GROUP = "SET_INTERACT_GROUP";
export const SET_INTERACT_PAGE = "SET_INTERACT_PAGE";
export const SET_INTERACT_MARKETPLACE = "SET_INTERACT_MARKETPLACE";
export const SET_INTERACT_NOTIFICATION = "SET_INTERACT_NOTIFICATION";
export const SET_INTERACT_SEARCH = "SET_INTERACT_SEARCH";